version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: russell-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: russell2000

  # 추후 백엔드/프론트엔드 서비스 추가 예정

